/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/LPaYaWy2qQl
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Yeseva_One } from 'next/font/google'

yeseva_one({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"

export function MyPPP() {
  return (
    <>
      <header className="w-full bg-gray-950 text-gray-50 py-6 px-4 md:px-6">
        <div className="container max-w-6xl mx-auto flex items-center justify-between">
          <Link className="flex items-center gap-2" href="#">
            <MagnetIcon className="w-8 h-8" />
            <span className="text-xl font-bold">Manga Portfolio</span>
          </Link>
          <nav className="hidden md:flex items-center gap-6">
            <Link className="hover:underline underline-offset-4" href="#">
              About
            </Link>
            <Link className="hover:underline underline-offset-4" href="#">
              Illustrations
            </Link>
            <Link className="hover:underline underline-offset-4" href="#">
              Comics
            </Link>
            <Link className="hover:underline underline-offset-4" href="#">
              Characters
            </Link>
            <Link className="hover:underline underline-offset-4" href="#">
              Contact
            </Link>
          </nav>
          <div className="flex items-center gap-4 md:hidden">
            <Button size="icon" variant="ghost">
              <MenuIcon className="w-6 h-6" />
              <span className="sr-only">Toggle menu</span>
            </Button>
          </div>
        </div>
      </header>
      <main>
        <section className="w-full bg-gray-950 text-gray-50 py-12 md:py-24 lg:py-32">
          <div className="container max-w-6xl mx-auto grid gap-8 md:grid-cols-2 items-center">
            <div className="space-y-4">
              <h1 className="text-4xl font-bold tracking-tight sm:text-5xl md:text-6xl">
                Welcome to my Manga Portfolio
              </h1>
              <p className="text-gray-400 max-w-[600px] md:text-xl">
                Explore my collection of manga-inspired illustrations, comics, and character designs.
              </p>
              <div className="flex gap-4">
                <Link
                  className="inline-flex items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-950 shadow-sm transition-colors hover:bg-gray-900/90 focus:outline-none focus:ring-2 focus:ring-gray-900 focus:ring-offset-2 dark:bg-gray-900 dark:text-gray-950 dark:hover:bg-gray-900/90 dark:focus:ring-gray-900 dark:bg-gray-50 dark:hover:bg-gray-50/90 dark:focus:ring-gray-50 dark:dark:bg-gray-50 dark:dark:hover:bg-gray-50/90 dark:dark:focus:ring-gray-50"
                  href="#"
                >
                  View Illustrations
                </Link>
                <Link
                  className="inline-flex items-center justify-center rounded-md border border-gray-200 border-gray-400 bg-transparent px-4 py-2 text-sm font-medium text-gray-400 shadow-sm transition-colors hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-400 focus:ring-offset-2 dark:border-gray-600 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:ring-gray-600 dark:border-gray-800"
                  href="#"
                >
                  Contact Me
                </Link>
              </div>
            </div>
            <div className="flex justify-center">
              <img
                alt="Manga Illustration"
                className="w-full max-w-[400px] md:max-w-none"
                height={600}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "600/600",
                  objectFit: "cover",
                }}
                width={600}
              />
            </div>
          </div>
        </section>
        <section className="w-full bg-gray-900 text-gray-50 py-12 md:py-24 lg:py-32" id="illustrations">
          <div className="container max-w-6xl mx-auto">
            <div className="space-y-4 mb-8">
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Manga-Style Illustrations</h2>
              <p className="text-gray-400 max-w-[600px] md:text-xl">
                Check out my collection of manga-inspired illustrations.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <img
                alt="Illustration 1"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Illustration 2"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Illustration 3"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Illustration 4"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Illustration 5"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Illustration 6"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
            </div>
          </div>
        </section>
        <section className="w-full bg-gray-950 text-gray-50 py-12 md:py-24 lg:py-32" id="comics">
          <div className="container max-w-6xl mx-auto">
            <div className="space-y-4 mb-8">
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Manga-Style Comics</h2>
              <p className="text-gray-400 max-w-[600px] md:text-xl">Explore my collection of manga-inspired comics.</p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <img
                alt="Comic 1"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Comic 2"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Comic 3"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Comic 4"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Comic 5"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Comic 6"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
            </div>
          </div>
        </section>
        <section className="w-full bg-gray-900 text-gray-50 py-12 md:py-24 lg:py-32" id="characters">
          <div className="container max-w-6xl mx-auto">
            <div className="space-y-4 mb-8">
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Manga-Style Character Designs</h2>
              <p className="text-gray-400 max-w-[600px] md:text-xl">
                Check out my collection of manga-inspired character designs.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <img
                alt="Character 1"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Character 2"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Character 3"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Character 4"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Character 5"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
              <img
                alt="Character 6"
                className="w-full h-auto rounded-lg object-cover"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
            </div>
          </div>
        </section>
        <section className="w-full bg-gray-950 text-gray-50 py-12 md:py-24 lg:py-32" id="about">
          <div className="container max-w-6xl mx-auto grid gap-8 md:grid-cols-2 items-center">
            <div className="flex justify-center">
              <img
                alt="Profile Image"
                className="w-full max-w-[300px] md:max-w-none rounded-full"
                height={400}
                src="/placeholder.svg"
                style={{
                  aspectRatio: "400/400",
                  objectFit: "cover",
                }}
                width={400}
              />
            </div>
            <div className="space-y-4">
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">About Me</h2>
              <p className="text-gray-400 max-w-[600px] md:text-xl">
                Hi, I'm a manga artist and illustrator with a passion for creating captivating characters and stories.
                I've been drawing manga-inspired art for over 10 years and have developed my own unique style. I'm
                excited to share my work with you and hope you enjoy exploring my portfolio.
              </p>
              <div className="flex gap-4">
                <Link
                  className="inline-flex items-center justify-center rounded-md bg-gray-900 px-4 py-2 text-sm font-medium text-gray-950 shadow-sm transition-colors hover:bg-gray-900/90 focus:outline-none focus:ring-2 focus:ring-gray-900 focus:ring-offset-2 dark:bg-gray-900 dark:text-gray-950 dark:hover:bg-gray-900/90 dark:focus:ring-gray-900 dark:bg-gray-50 dark:hover:bg-gray-50/90 dark:focus:ring-gray-50 dark:dark:bg-gray-50 dark:dark:hover:bg-gray-50/90 dark:dark:focus:ring-gray-50"
                  href="#"
                >
                  Contact Me
                </Link>
                <Link
                  className="inline-flex items-center justify-center rounded-md border border-gray-200 border-gray-400 bg-transparent px-4 py-2 text-sm font-medium text-gray-400 shadow-sm transition-colors hover:bg-gray-800 focus:outline-none focus:ring-2 focus:ring-gray-400 focus:ring-offset-2 dark:border-gray-600 dark:text-gray-400 dark:hover:bg-gray-800 dark:focus:ring-gray-600 dark:border-gray-800"
                  href="#"
                >
                  View Resume
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full bg-gray-900 text-gray-50 py-12 md:py-24 lg:py-32" id="contact">
          <div className="container max-w-6xl mx-auto">
            <div className="space-y-4 mb-8">
              <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Get in Touch</h2>
              <p className="text-gray-400 max-w-[600px] md:text-xl">
                I'd love to hear from you! Feel free to reach out with any questions or inquiries.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
              <div className="bg-gray-950 rounded-lg p-6 space-y-4">
                <MailIcon className="w-8 h-8" />
                <h3 className="text-xl font-bold">Email</h3>
                <a className="text-gray-400 hover:underline" href="#">
                  example@example.com
                </a>
              </div>
              <div className="bg-gray-950 rounded-lg p-6 space-y-4">
                <PhoneIcon className="w-8 h-8" />
                <h3 className="text-xl font-bold">Phone</h3>
                <a className="text-gray-400 hover:underline" href="#">
                  +1 (234) 567-890
                </a>
              </div>
              <div className="bg-gray-950 rounded-lg p-6 space-y-4">
                <FacebookIcon className="w-8 h-8" />
                <h3 className="text-xl font-bold">Social Media</h3>
                <div className="flex gap-4">
                  <Link className="text-gray-400 hover:underline" href="#">
                    Twitter
                  </Link>
                  <Link className="text-gray-400 hover:underline" href="#">
                    Instagram
                  </Link>
                  <Link className="text-gray-400 hover:underline" href="#">
                    Behance
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="w-full bg-gray-950 text-gray-50 py-6 px-4 md:px-6">
        <div className="container max-w-6xl mx-auto flex items-center justify-between">
          <div className="text-sm">© 2024 Manga Portfolio. All rights reserved.</div>
          <nav className="hidden md:flex items-center gap-6">
            <Link className="hover:underline underline-offset-4" href="#">
              Privacy Policy
            </Link>
            <Link className="hover:underline underline-offset-4" href="#">
              Terms of Service
            </Link>
          </nav>
        </div>
      </footer>
    </>
  )
}

function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function MagnetIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 15-4-4 6.75-6.77a7.79 7.79 0 0 1 11 11L13 22l-4-4 6.39-6.36a2.14 2.14 0 0 0-3-3L6 15" />
      <path d="m5 8 4 4" />
      <path d="m12 15 4 4" />
    </svg>
  )
}


function MailIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="16" x="2" y="4" rx="2" />
      <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
    </svg>
  )
}


function MenuIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function PhoneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z" />
    </svg>
  )
}
